### ISSUE TITLE
tests does not run, package does not appear in maven central

### ISSUE THREAD

**Issue by cesarpachon** [hamnis/json-stat.java#1]
hello! trying to use json-stat.java.. when running mvn test, it says 0 test run.. and when trying to use it in a new project, as a dependency, the classes are not found. 

I am trying the dependency as this: 

```
<dependency>
  <groupId>net.hamnaberg.json</groupId>
  <artifactId>json-stat.java</artifactId>
  <version>0.1.0-SNAPSHOT</version>
</dependency>
```

**Comment by hamnis** [comment]
Well, since this was an experiment, i never did think about releasing it.
If someone want to take over, please do.
